language: java
jdk: oraclejdk8

node_js: - "0.12"

cache:
  directories:
   # - $HOME/.m2
   # - node_modules

script:
  - mvn verify -Ptest

before_install:
  - npm install 
  - nvm install

install : 
  - npm install 
  - nvm install

after_success:
  - surge --project ./target/site --domain mycooldoc.surge.sh
after_failure:
  #Remove documentation for a failing project
  - surge teardown mycooldoc.surge.sh
