language: java
jdk: oraclejdk8

node_js: 
  - "stable"

cache:
  directories:
    - $HOME/.m2
    - node_modules

before_install:
  - npm install 
  - nvm install

install : 
  - npm install 
  - nvm install

script:
  - mvn verify -Ptest



after_failure:
  #Remove documentation for a failing project
  - surge teardown mycooldoc.surge.sh
