language: java
jdk: oraclejdk8

#node_js:  -"stable"
env:
  - NODE_VERSION="stable"

cache:
  directories:
    - $HOME/.m2
    - node_modules

before_install:
  - nvm install $NODE_VERSION
  - nvn install
  - npm install 


script:
  - mvn verify -Ptest

after_success:
  #- npn run surge
  - surge --project ./target/site --domain mycooldoc.surge.sh

after_failure:
  #Remove documentation for a failing project
  - surge teardown mycooldoc.surge.sh
