language: java
jdk: oraclejdk8

#node_js:  -"stable"
env:
  - NODE_VERSION="10.15.0"

# cache:
  # directories:
    # - $HOME/.m2
    # - node_modules

before_install:
  - nvm install $NODE_VERSION
  - npm install 


script:
  - mvn verify -Ptest

after_success:
  - nvm install $NODE_VERSION
  - npm install 
  - npm run surge
  - surge --project ./target/site --domain mycooldoc.surge.sh

after_failure:
  #Remove documentation for a failing project
  - surge teardown mycooldoc.surge.sh
